"""
scripts/viz/trace_stats.py
==========================
Trajectory statistics from Phase 0R trace JSONL:

  - path length distribution
  - backtrack count distribution
  - kappa distribution per agent
  - early-termination rate

Outputs:
  results/figures/trace_path_lengths.png
  results/figures/trace_kappa_by_agent.png
  paper/auto_trace_stats.tex

Usage:
  python scripts/viz/trace_stats.py --traces artifacts/observe_traces/phase0r_traces.jsonl
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, ROOT)

from scripts.viz._common import (
    ensure_dirs, fig_path, figure_includegraphics, get_mpl,
    have_matplotlib, write_tex,
)


def parse_args():
    p = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    p.add_argument("--traces", required=True,
                   help="Path to phase0r_traces.jsonl")
    p.add_argument("--name", default="trace_stats")
    p.add_argument("--limit", type=int, default=0,
                   help="Cap on number of traces read (0 = all)")
    return p.parse_args()


def _aggregate(path: str, limit: int = 0) -> dict:
    path_lens: list = []
    backtracks: list = []
    early_term: int = 0
    n_traces: int   = 0
    kappa_by_agent: dict = defaultdict(Counter)
    n_deltas_final: list = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            n_traces += 1
            path_lens.append(len(rec.get("path") or []))
            backtracks.append(int(rec.get("backtrack_count") or 0))
            if rec.get("early_terminated"):
                early_term += 1
            for step in rec.get("context_buffer") or []:
                ag = step.get("agent_name", "?")
                ka = (step.get("confidence") or "medium").lower()
                kappa_by_agent[ag][ka] += 1
            n_deltas_final.append(len(rec.get("final_deltas") or []))
            if limit and n_traces >= limit:
                break
    return {
        "n_traces":         n_traces,
        "path_lens":        path_lens,
        "backtracks":       backtracks,
        "early_term":       early_term,
        "kappa_by_agent":   kappa_by_agent,
        "n_deltas_final":   n_deltas_final,
    }


def _plot_path_lengths(plt, path_lens: list, out_png: Path) -> bool:
    if not path_lens:
        return False
    fig, ax = plt.subplots(figsize=(7, 4))
    max_p = max(path_lens)
    ax.hist(path_lens, bins=list(range(1, max_p + 2)), color="#5E35B1", edgecolor="white")
    ax.set_xlabel("Path length")
    ax.set_ylabel("Number of traces")
    ax.set_title("Phase 0R trace path-length distribution")
    fig.savefig(out_png, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return True


def _plot_kappa_by_agent(plt, kappa_by_agent: dict, out_png: Path) -> bool:
    if not kappa_by_agent:
        return False
    agents = list(kappa_by_agent.keys())
    levels = ["high", "medium", "low"]
    colors = {"high": "#43A047", "medium": "#FB8C00", "low": "#E53935"}

    fig, ax = plt.subplots(figsize=(8, 4))
    width = 0.25
    import numpy as np
    x = np.arange(len(agents))
    for i, lvl in enumerate(levels):
        ys = [kappa_by_agent[a].get(lvl, 0) for a in agents]
        ax.bar(x + (i - 1) * width, ys, width, label=lvl, color=colors[lvl])
    ax.set_xticks(x)
    ax.set_xticklabels(agents, rotation=20, ha="right", fontsize=9)
    ax.set_ylabel("Count")
    ax.set_title("Per-agent kappa distribution across traces")
    ax.legend()
    fig.savefig(out_png, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return True


def _build_tex(name: str, stats: dict, figures_written: list) -> str:
    lines: list = []
    lines.append(r"% Auto-generated by scripts/viz/trace_stats.py — do not edit by hand.")
    lines.append("")
    n_t = stats["n_traces"]
    if n_t:
        early_pct = 100.0 * stats["early_term"] / n_t
        avg_len = sum(stats["path_lens"]) / n_t
        avg_bt  = sum(stats["backtracks"]) / n_t
        avg_nd  = (sum(stats["n_deltas_final"]) / n_t) if stats["n_deltas_final"] else 0.0
        lines.append(r"\begin{table}[t]")
        lines.append(r"  \centering\small")
        lines.append(r"  \begin{tabular}{lr}")
        lines.append(r"    \toprule")
        lines.append(r"    Metric & Value \\")
        lines.append(r"    \midrule")
        lines.append(f"    Traces analysed       & {n_t} \\\\")
        lines.append(f"    Mean path length      & {avg_len:.2f} \\\\")
        lines.append(f"    Mean backtracks       & {avg_bt:.2f} \\\\")
        lines.append(f"    Mean final deltas     & {avg_nd:.2f} \\\\")
        lines.append(f"    Early termination     & {early_pct:.1f}\\% \\\\")
        lines.append(r"    \bottomrule")
        lines.append(r"  \end{tabular}")
        lines.append(r"  \caption{Phase 0R trace summary statistics.}")
        lines.append(r"  \label{tab:trace_stats}")
        lines.append(r"\end{table}")
        lines.append("")
    for fig_name, caption, label in figures_written:
        lines.append(figure_includegraphics(fig_name, caption, label))
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    ensure_dirs()
    if not Path(args.traces).is_file():
        raise SystemExit(f"trace JSONL not found: {args.traces}")
    stats = _aggregate(args.traces, args.limit)
    print(f"=== trace stats === ({stats['n_traces']} traces)")
    print(f"  mean path length : {sum(stats['path_lens']) / max(1, stats['n_traces']):.2f}")
    print(f"  mean backtracks  : {sum(stats['backtracks']) / max(1, stats['n_traces']):.2f}")
    print(f"  early term       : {stats['early_term']}/{stats['n_traces']}")

    figures_written: list = []
    if have_matplotlib():
        _, plt = get_mpl()
        for tag, fn, data, caption, label in [
            ("trace_path_lengths", _plot_path_lengths,    stats["path_lens"],
             "Distribution of routed-swarm trace path lengths.",
             "trace_path_lengths"),
            ("trace_kappa_by_agent", _plot_kappa_by_agent, stats["kappa_by_agent"],
             "Per-agent kappa (confidence) distribution across all traces.",
             "trace_kappa_agent"),
        ]:
            out_png = fig_path(tag)
            if fn(plt, data, out_png):
                print(f"  wrote {out_png}")
                figures_written.append((tag, caption, label))
    else:
        print("  matplotlib not installed — table-only output")

    tex_out = write_tex(args.name, _build_tex(args.name, stats, figures_written))
    print(f"  wrote {tex_out}")


if __name__ == "__main__":
    main()
