#!/usr/bin/env python3
"""
scripts/sync_pathome_metrics.py
===============================
Read pathome_eval.json under each results directory and emit
``plantswarm/latex/auto_pathome_metrics.tex`` — a small file of
\\newcommand macros referenced (or copy-pasted) by the hardcoded
tables in the new paper:

  \\PathomePvECE         e.g. 0.12
  \\PathomePwECE         e.g. 0.17
  \\PathomePvTthreeF     T3 F1 on PV (seen)
  \\PathomePwTthreeF     T3 F1 on PW
  \\PathomeUnseenTthreeF T3 F1 on the 12 unseen PV classes (paper P5)
  \\PathomeTPCP          tokens-per-correct-prediction

Usage:
    python scripts/sync_pathome_metrics.py \\
      --pv-results results/plantvillage_full/pathome_eval.json \\
      --pw-results results/plantwild_full/pathome_eval.json \\
      --out plantswarm/latex/auto_pathome_metrics.tex
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


def fmt(x: float, decimals: int = 2) -> str:
    if x is None:
        return "---"
    return f"{x:.{decimals}f}"


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--pv-results", default="results/plantvillage_full/pathome_eval.json")
    p.add_argument("--pw-results", default="results/plantwild_full/pathome_eval.json")
    p.add_argument("--out", default="plantswarm/latex/auto_pathome_metrics.tex")
    return p.parse_args()


def load_or_warn(path: str) -> dict:
    if not os.path.exists(path):
        print(f"  [warn] missing {path} — emitting --- placeholders", file=sys.stderr)
        return {}
    with open(path) as f:
        return json.load(f)


def main() -> None:
    args = parse_args()
    pv = load_or_warn(args.pv_results)
    pw = load_or_warn(args.pw_results)

    pv_t3_f1 = pv.get("T3", {}).get("macro_f1")
    pv_ece = pv.get("T3", {}).get("ece")
    pv_tpcp = pv.get("T3", {}).get("tpcp")

    pw_t3_f1 = pw.get("T3", {}).get("macro_f1")
    pw_ece = pw.get("T3", {}).get("ece")
    pw_tpcp = pw.get("T3", {}).get("tpcp")

    pv_unseen = pv.get("T3_slices", {}).get("unseen", {}).get("macro_f1")

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "% Auto-generated by scripts/sync_pathome_metrics.py — do not edit by hand.",
        f"% Generated at {ts}",
        f"\\newcommand{{\\PathomePvECE}}{{{fmt(pv_ece, 2)}}}",
        f"\\newcommand{{\\PathomePwECE}}{{{fmt(pw_ece, 2)}}}",
        f"\\newcommand{{\\PathomePvTthreeF}}{{{fmt(pv_t3_f1, 1)}}}",
        f"\\newcommand{{\\PathomePwTthreeF}}{{{fmt(pw_t3_f1, 1)}}}",
        f"\\newcommand{{\\PathomeUnseenTthreeF}}{{{fmt(pv_unseen, 1)}}}",
        f"\\newcommand{{\\PathomePvTPCP}}{{{fmt(pv_tpcp, 0)}}}",
        f"\\newcommand{{\\PathomePwTPCP}}{{{fmt(pw_tpcp, 0)}}}",
        "",
    ]

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path}")
    for ln in lines:
        if ln.startswith("\\newcommand"):
            print(f"  {ln}")


if __name__ == "__main__":
    main()
