"""
agents/base_agent.py
====================
Base class for the Qwen visual-symptom swarm.

The swarm focuses **exclusively on visual symptoms** — the canonical KB
already carries pathogen / type / treatments / cultural-control info
generated by Claude in Phase 0; the Qwen swarm's only job is to look at
ONE field photograph and produce image-grounded deltas against the
canonical visual_symptoms block.

The swarm is decomposed into **24 single-feature specialists** + one
``VisualDiagnosisAgent`` consolidator. Each specialist owns ONE delta
field and asks a single laser-focused question about the photograph,
following the chain-of-thought pattern documented in
``DR.Arti.docx``
(per-step decisive forks, e.g. "Is the lower stem pith white or brown?
white -> SDS, brown -> BSR").

Delta schema (matches pathome.RegionalDelta):
    {
      "field":          str,   # one of ALLOWED_DELTA_FIELDS
      "canonical_says": str,   # short quote, or "(not specified)"
      "image_shows":    str,   # what the photo shows that adds / contradicts
      "image_quote":    str,   # one-sentence visual evidence
    }
"""

from __future__ import annotations

import abc
import json
import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple

if TYPE_CHECKING:
    # Only needed for type hints; defer the runtime import so the agent
    # classes can be imported in environments that don't have `requests`.
    from utils.vllm_client import VLLMClient


# ---------------------------------------------------------------------------
# Visual-only delta field vocabulary (24 fields + "other")
# ---------------------------------------------------------------------------

ALLOWED_DELTA_FIELDS: Tuple[str, ...] = (
    # Leaf features (8) — the doc's CoT spends most time on these
    "leaf_lesion_shape",     # circular / angular / irregular / elongated
    "leaf_lesion_color",     # specific color description (palette / hex / common-name)
    "leaf_lesion_texture",   # sunken / raised / smooth / fuzzy / leathery
    "leaf_chlorosis",        # interveinal / marginal / generalized / mosaic
    "leaf_necrosis",         # tip / margin / spot / extending-from-vein
    "leaf_curl",             # curling / blistering / puckering / cupping
    "leaf_vein_pattern",     # vein clearing / vein necrosis / vein-aligned spots
    "leaf_geometry",         # leaf shape / length-to-width / serration / lobation
    # Stem features (4) — decisive in look-alikes like SDS vs BSR
    "stem_lesion",           # cankers / girdling / sunken-raised on stem surface
    "stem_pith",             # internal pith color when split (white / brown / cardboard-like)
    "stem_surface",          # galls / blisters / scabs / exudates on outer stem
    "stem_discoloration",    # vascular streaking / browning visible through bark
    # Root + crown (2)
    "root_visible",          # rot / color / cysts / blue fungal masses on visible roots
    "crown_collar",          # crown / soil-line lesions / girdling at collar
    # Reproductive (2)
    "flower",                # flower blight / distortion / discoloration
    "fruit",                 # fruit lesions / mummification / scab
    # Signs vs symptoms (1)
    "sporulation",           # mycelium / spore masses / fruiting bodies / bacterial ooze
    # Whole-plant patterns (3) — top-down spatial reasoning
    "wilting",               # whole-plant / one-side / hemispheric / branch-localized
    "defoliation",           # leaf drop pattern + whether petioles remain attached
    "spatial_pattern",       # within-canopy or within-field distribution
    # Diagnostic cross-cutters (4)
    "concentric_pattern",    # target spots / halos / concentric rings
    "color_palette",         # dominant + secondary lesion-area colors (palette encoder)
    "look_alikes_visual",    # CoT decision-graph against known confusable diseases
    "severity_visible",      # fraction of organ affected (low / medium / high) by visible area
    "other",
)

CONFIDENCE_LEVELS = ("high", "medium", "low")


# Map each delta field to the canonical KB key(s) the specialist should
# consult when comparing the image to baseline KB text. All map to the
# Phase 0 visual_symptoms block — never to non-visual fields.
_DELTA_FIELD_TO_CANONICAL: Dict[str, Tuple[str, ...]] = {
    # Leaf
    "leaf_lesion_shape":     ("summary", "diagnostic_features"),
    "leaf_lesion_color":     ("summary",),
    "leaf_lesion_texture":   ("summary",),
    "leaf_chlorosis":        ("summary", "diagnostic_features"),
    "leaf_necrosis":         ("summary",),
    "leaf_curl":             ("summary",),
    "leaf_vein_pattern":     ("diagnostic_features",),
    "leaf_geometry":         ("look_alikes",),
    # Stem
    "stem_lesion":           ("summary", "diagnostic_features"),
    "stem_pith":             ("diagnostic_features",),
    "stem_surface":          ("summary",),
    "stem_discoloration":    ("diagnostic_features",),
    # Root + crown
    "root_visible":          ("diagnostic_features",),
    "crown_collar":          ("summary",),
    # Reproductive
    "flower":                ("summary",),
    "fruit":                 ("summary",),
    # Signs
    "sporulation":           ("diagnostic_features",),
    # Patterns
    "wilting":               ("summary",),
    "defoliation":           ("summary", "diagnostic_features"),
    "spatial_pattern":       ("summary",),
    # Diagnostic cross-cutters
    "concentric_pattern":    ("diagnostic_features",),
    "color_palette":         ("summary",),
    "look_alikes_visual":    ("look_alikes",),
    "severity_visible":      (),
    "other":                 (),
}


# ---------------------------------------------------------------------------
# Output dataclass
# ---------------------------------------------------------------------------

@dataclass
class AgentDeltaOutput:
    agent_name: str
    deltas: List[Dict[str, str]] = field(default_factory=list)
    confidence: str = "medium"
    reasoning: str = ""
    raw_text: str = ""
    # Round-2 only: actions this agent took against peers' round-1
    # outputs (stigmergy). Empty in round 1.
    cross_refs: List[Dict[str, str]] = field(default_factory=list)
    # Which swarm round produced this output (1-indexed).
    round_idx: int = 1


# Alias for clarity — the shared blackboard is a dict from agent name
# to that agent's most recent AgentDeltaOutput. Round 2 sees this.
Blackboard = Dict[str, AgentDeltaOutput]


# Valid actions an agent can declare against a peer's round-1 output.
CROSS_REF_ACTIONS = ("support", "challenge", "withdraw")


# ---------------------------------------------------------------------------
# Validation helpers (used by parse_agent_output + by tests)
# ---------------------------------------------------------------------------

def _clean(s: Any) -> str:
    if s is None:
        return ""
    if isinstance(s, list):
        return "; ".join(str(x) for x in s if x is not None and str(x).strip())
    return str(s).strip()


def _validate_delta(d: Any, allowed_fields: set) -> Optional[Dict[str, str]]:
    if not isinstance(d, dict):
        return None
    image_shows = _clean(d.get("image_shows"))
    if not image_shows:
        return None
    fld = _clean(d.get("field")).lower() or "other"
    if fld not in allowed_fields:
        fld = "other"
    return {
        "field":          fld,
        "canonical_says": _clean(d.get("canonical_says")) or "(not specified)",
        "image_shows":    image_shows,
        "image_quote":    _clean(d.get("image_quote")),
    }


def _canonical_quote_for_field(
    field: str,
    canonical: Dict[str, Any],
    max_chars: int = 240,
) -> str:
    """Map a delta ``field`` to the canonical visual_symptoms slice it
    came from and return a short quote suitable for ``canonical_says``.

    Returns ``"(not specified)"`` when the canonical KB has no usable
    text for the slice(s) this field is mapped to (see
    ``_DELTA_FIELD_TO_CANONICAL``).
    """
    if not isinstance(canonical, dict):
        return "(not specified)"
    keys = _DELTA_FIELD_TO_CANONICAL.get(field, ())
    for key in (*keys, "summary", "diagnostic_features"):
        v = _clean(canonical.get(key))
        if v:
            if len(v) > max_chars:
                v = v[:max_chars].rstrip() + "..."
            return v
    return "(not specified)"


def _backfill_canonical_says(
    deltas: List[Dict[str, str]],
    canonical: Dict[str, Any],
) -> List[Dict[str, str]]:
    """In-place: replace ``canonical_says == "(not specified)"`` with a
    real quote from the canonical KB when the delta's ``field`` maps to
    a populated canonical slice. Qwen-VL frequently emits the fallback
    string even when the canonical text is right there in the prompt
    (the "do NOT restate" instruction biases it toward the safe
    default), so we patch the trace deterministically.
    """
    for d in deltas:
        if not isinstance(d, dict):
            continue
        cs = _clean(d.get("canonical_says"))
        if cs and cs != "(not specified)":
            continue
        quote = _canonical_quote_for_field(d.get("field", "other"), canonical)
        if quote and quote != "(not specified)":
            d["canonical_says"] = quote
        else:
            d["canonical_says"] = "(not specified)"
    return deltas


def _coerce_confidence(c: Any) -> str:
    s = _clean(c).lower()
    if s in CONFIDENCE_LEVELS:
        return s
    tokens = re.findall(r"[a-z]+", s)
    for level in CONFIDENCE_LEVELS:
        if level in tokens:
            return level
    return "medium"


def _validate_cross_ref(d: Any) -> Optional[Dict[str, str]]:
    """Validate one cross-reference action (round-2 only).

    Schema:
      {"action": "<support|challenge|withdraw>",
       "target_agent": "<peer AGENT_NAME or null>",
       "rationale":    "<one sentence>"}
    """
    if not isinstance(d, dict):
        return None
    action = _clean(d.get("action")).lower()
    if action not in CROSS_REF_ACTIONS:
        return None
    rationale = _clean(d.get("rationale"))
    if not rationale:
        return None
    return {
        "action":       action,
        "target_agent": _clean(d.get("target_agent")),  # "" allowed for self-withdraw
        "rationale":    rationale,
    }


def parse_agent_output(
    text: str,
    owned_fields: List[str],
) -> Tuple[List[Dict[str, str]], str, str, List[Dict[str, str]]]:
    """Return (deltas, confidence, reasoning, cross_refs).

    Accepts strict JSON, JSON wrapped in markdown fences, or a JSON
    object embedded in surrounding prose (best-effort regex pull).

    ``cross_refs`` is round-2 only — agents may declare ``support``,
    ``challenge``, or ``withdraw`` actions against round-1 peers.
    Always returned as a list (empty in round 1).
    """
    if not text:
        return [], "medium", "", []
    s = text.strip()
    if s.startswith("```"):
        s = re.sub(r"^```(?:json)?\s*", "", s)
        s = re.sub(r"\s*```$", "", s)
    obj: Any = None
    try:
        obj = json.loads(s)
    except json.JSONDecodeError:
        m = re.search(r"\{.*\}", s, re.DOTALL)
        if m:
            try:
                obj = json.loads(m.group())
            except json.JSONDecodeError:
                obj = None
    if not isinstance(obj, dict):
        return [], "medium", "", []
    allowed_fields = set(owned_fields) | {"other"}
    deltas: List[Dict[str, str]] = []
    for d in obj.get("deltas") or []:
        v = _validate_delta(d, allowed_fields)
        if v is not None:
            deltas.append(v)
    cross_refs: List[Dict[str, str]] = []
    for d in obj.get("cross_refs") or []:
        v = _validate_cross_ref(d)
        if v is not None:
            cross_refs.append(v)
    confidence = _coerce_confidence(obj.get("confidence"))
    reasoning  = _clean(obj.get("reasoning"))
    return deltas, confidence, reasoning, cross_refs


# ---------------------------------------------------------------------------
# Prompt template — embeds the decision-graph CoT pattern from the doc
# ---------------------------------------------------------------------------

DELTA_USER_PROMPT = """\
You are looking at ONE Bugwood Network field photograph of a plant
disease. Canonical KB text for this disease is given below along with
any prior image-grounded observations for THIS state.

Crop:    {crop}
Disease: {disease}
State:   {state}

CANONICAL KB (visual_symptoms slice for {agent_name} — do NOT restate):
{canonical_slice}
{existing_kb_block}\
Your job is the SINGLE focused question this specialist owns:

    {focus_question}

Walk a brief chain-of-thought before answering:
  1. Identify what {agent_name} can actually see in this image
     (anatomical structure or pattern your specialty cares about).
  2. Compare against canonical KB text above. Is the photo showing
     something canonical does NOT capture? Or contradicting it?
  3. Only if step 2 is YES, emit a delta. Restating canonical or the
     prior observations is FORBIDDEN. Confirming canonical => no delta.
Each delta MUST be supported by something visibly grounded in this
photograph. If the image is too blurred / wrong organ visible / cropped
to omit the structure you care about, return an empty deltas list and
confidence "low".

You own these delta fields: {owned_fields}

Confidence guide:
  - "high"   : clear visual evidence, unambiguous
  - "medium" : visible but partially obscured / inferred
  - "low"    : image is not informative for your specialty

Output STRICT JSON, no markdown fences, no preamble:
{{
  "deltas": [
    {{
      "field":          "<one of: {owned_fields}>",
      "canonical_says": "<short quote from canonical above, or '(not specified)'>",
      "image_shows":    "<state-specific addition or contradiction — one sentence>",
      "image_quote":    "<one-sentence visual evidence — what in the pixels supports this>"
    }}
  ],
  "confidence": "high" | "medium" | "low",
  "reasoning":  "<one-line CoT trace: I saw X, canonical says Y, therefore Z>"
}}

If the photo confirms canonical AND existing KB exactly, return
{{"deltas": [], "confidence": "high", "reasoning": "...confirms canonical..."}}.
"""


# Round-2 prompt: the agent sees the BLACKBOARD (every peer's round-1
# output) and may now refine, support a peer, challenge a peer, or
# withdraw its own round-1 delta. This is the "real swarm" behavior —
# stigmergy via a shared trace plus cross-agent coordination.
DELTA_USER_PROMPT_R2 = """\
You are looking at the SAME Bugwood Network field photograph you saw
in round 1. This is ROUND 2 of the swarm pass.

Crop:    {crop}
Disease: {disease}
State:   {state}

CANONICAL KB (visual_symptoms slice for {agent_name} — do NOT restate):
{canonical_slice}
{existing_kb_block}\

PEER BLACKBOARD (every specialist's round-1 output is below — read
these carefully; they are observations from siblings looking at the
SAME photograph through different organ-family lenses):
{blackboard_block}

Your specialty owns these delta fields: {owned_fields}
Your focused question (unchanged from round 1):

    {focus_question}

Round-2 chain-of-thought:
  1. Re-examine the photograph for YOUR specialty.
  2. Read the BLACKBOARD. Do any peer observations strengthen,
     contradict, or contextualize your round-1 finding?
       - Example STRENGTHEN: StemPithAgent says "white pith";
         DefoliationAgent says "bare petioles attached" — both point
         to SDS. If you're LookAlikeCoTAgent, this strengthens an
         SDS-over-BSR challenge.
       - Example CONTRADICT: you reported "tan lesion centers" but
         ColorPaletteAgent reports "olive-green dominant" — you
         should challenge them, withdraw, or refine.
  3. Decide:
       - REFINE: emit a tighter / better-grounded delta replacing
         your round-1 output. Set "deltas" to the new version.
       - WITHDRAW: leave "deltas" empty; declare a withdraw
         cross_ref against your own AGENT_NAME with a rationale.
       - NEW: emit a NEW delta you missed in round 1, prompted by
         what a peer observed.
       - SUPPORT a peer: add a cross_ref with action "support" and
         target_agent = the peer's AGENT_NAME.
       - CHALLENGE a peer: add a cross_ref with action "challenge"
         and target_agent = the peer's AGENT_NAME.

Restating canonical OR another agent's exact observation is FORBIDDEN.
Your round-2 deltas must add information beyond what canonical and the
blackboard already say.

Output STRICT JSON, no markdown fences, no preamble:
{{
  "deltas": [
    {{
      "field":          "<one of: {owned_fields}>",
      "canonical_says": "<short quote from canonical above, or '(not specified)'>",
      "image_shows":    "<what the photo shows — one sentence>",
      "image_quote":    "<one-sentence visual evidence>"
    }}
  ],
  "cross_refs": [
    {{
      "action":       "support" | "challenge" | "withdraw",
      "target_agent": "<peer AGENT_NAME (e.g. StemPithAgent), or your OWN name for withdraw>",
      "rationale":    "<one-sentence justification>"
    }}
  ],
  "confidence": "high" | "medium" | "low",
  "reasoning":  "<one-line CoT trace: peer X said Y so I now Z>"
}}

If round-2 reading of the blackboard yields nothing to refine,
challenge, or support — emit an empty deltas + empty cross_refs and
return confidence "medium" with a rationale that points at the
unchanged round-1 output.
"""


# ---------------------------------------------------------------------------
# Base agent
# ---------------------------------------------------------------------------

class BaseAgent(abc.ABC):
    """Subclasses MUST set AGENT_NAME, OWNED_FIELDS, SYSTEM_PROMPT,
    and FOCUS_QUESTION.

    Specialists are invoked in parallel by ``plantswarm.delta_pipeline`` —
    no routing or handoff state lives on the agent itself.
    """

    AGENT_NAME: str = "BaseAgent"
    OWNED_FIELDS: List[str] = []
    SYSTEM_PROMPT: str = (
        "You are a plant pathology vision specialist. Output strict "
        "JSON only — no prose, no markdown, no preamble."
    )
    FOCUS_QUESTION: str = (
        "What does the image show for your specialty that the canonical "
        "KB does not already capture?"
    )

    def __init__(self, client: "VLLMClient"):
        self.client = client

    def extract_deltas(
        self,
        *,
        crop: str,
        disease: str,
        state: str,
        canonical: Dict[str, Any],
        image_data_url: str,
        existing_kb_deltas: Optional[List[Dict[str, Any]]] = None,
        seed: Optional[int] = None,
        temperature: Optional[float] = None,
        blackboard: Optional[Blackboard] = None,
        round_idx: int = 1,
    ) -> AgentDeltaOutput:
        """One specialist pass — returns deltas + confidence + reasoning
        (+ cross_refs in round 2).

        Round 1 (``blackboard=None``, ``round_idx=1``): independent
        observation. Standard prompt.

        Round 2 (``blackboard`` populated): stigmergy round. The agent
        sees every peer's round-1 output and may refine its own delta,
        emit a new delta prompted by peer observations, or declare
        support / challenge / withdraw cross_refs.
        """
        canonical_slice = self._format_canonical_slice(canonical)
        existing_block  = self._format_existing_kb(existing_kb_deltas or [], state)
        owned_list      = ", ".join(self.OWNED_FIELDS) or "other"

        if blackboard:
            user_prompt = DELTA_USER_PROMPT_R2.format(
                crop=crop, disease=disease, state=state,
                agent_name=self.AGENT_NAME,
                canonical_slice=canonical_slice,
                existing_kb_block=existing_block,
                blackboard_block=self._format_blackboard(blackboard, exclude=self.AGENT_NAME),
                owned_fields=owned_list,
                focus_question=self.FOCUS_QUESTION,
            )
        else:
            user_prompt = DELTA_USER_PROMPT.format(
                crop=crop, disease=disease, state=state,
                agent_name=self.AGENT_NAME,
                canonical_slice=canonical_slice,
                existing_kb_block=existing_block,
                owned_fields=owned_list,
                focus_question=self.FOCUS_QUESTION,
            )
        messages = [{
            "role": "user",
            "content": [
                {"type": "image_url", "image_url": {"url": image_data_url}},
                {"type": "text",      "text":      user_prompt},
            ],
        }]
        text, _tokens = self.client.chat(
            messages=messages, system_prompt=self.SYSTEM_PROMPT,
            seed=seed, temperature=temperature,
        )
        deltas, confidence, reasoning, cross_refs = parse_agent_output(
            text=text, owned_fields=self.OWNED_FIELDS,
        )
        _backfill_canonical_says(deltas, canonical)
        return AgentDeltaOutput(
            agent_name=self.AGENT_NAME,
            deltas=deltas, confidence=confidence, reasoning=reasoning,
            raw_text=text,
            cross_refs=cross_refs,
            round_idx=round_idx,
        )

    # Backwards-compat alias for tests / external callers.
    extract_with_routing = extract_deltas

    # ------------------------------------------------------------------
    # Context rendering
    # ------------------------------------------------------------------

    def _format_canonical_slice(self, canonical: Dict[str, Any]) -> str:
        """Render only the visual-symptoms slice of canonical, prefixed
        with pathogen + type as context (so the specialist knows what
        signs to expect — e.g., fungal sporulation vs bacterial ooze)."""
        lines: List[str] = []
        if canonical.get("pathogen_scientific_name"):
            lines.append(f"  pathogen: {_clean(canonical['pathogen_scientific_name'])}")
        if canonical.get("type_of_disease"):
            lines.append(f"  type:     {_clean(canonical['type_of_disease'])}")
        # Always include the visual-symptoms triad as baseline:
        for visual_key in ("summary", "diagnostic_features", "look_alikes"):
            v = canonical.get(visual_key)
            if v:
                lines.append(f"  {visual_key}: {_clean(v)}")
        return "\n".join(lines) if lines else "  (canonical visual_symptoms not available)"

    @staticmethod
    def _format_blackboard(
        blackboard: Blackboard,
        *,
        exclude: Optional[str] = None,
    ) -> str:
        """Render every peer's round-1 output for the round-2 prompt.

        ``exclude`` is the calling agent's own AGENT_NAME, so a
        specialist doesn't have to read its own round-1 output back
        verbatim (it's already in conversation context).
        """
        lines: List[str] = []
        for name in sorted(blackboard):
            if exclude and name == exclude:
                continue
            out = blackboard[name]
            tag = f"(confidence={out.confidence})"
            lines.append(f"  - {name} {tag}")
            if out.reasoning:
                lines.append(f"      reasoning: {out.reasoning}")
            if not out.deltas:
                lines.append("      (no deltas in round 1)")
                continue
            for d in out.deltas:
                lines.append(
                    f"      [{d.get('field','')}] "
                    f"{d.get('image_shows','')!s}"
                )
        if not lines:
            return "  (blackboard is empty)"
        return "\n".join(lines)

    @staticmethod
    def _format_existing_kb(
        existing: List[Dict[str, Any]],
        state: str,
    ) -> str:
        if not existing:
            return ""
        lines = ["", f"EXISTING KB OBSERVATIONS for {state} "
                     f"(from prior runs — preserve, do NOT restate):"]
        for d in existing:
            fld = d.get("field", "other")
            support = d.get("__support__") or d.get("support") or d.get("swarm_support") or 0
            tag = f" (support={support})" if support else ""
            shows = d.get("image_shows", "")
            if len(shows) > 220:
                shows = shows[:220].rstrip() + "..."
            lines.append(f"  - [{fld}]{tag}")
            if d.get("canonical_says") and d["canonical_says"] != "(not specified)":
                lines.append(f"      canonical: {d['canonical_says']}")
            lines.append(f"      previously observed: {shows}")
        lines.append("")
        return "\n".join(lines) + "\n"
