#!/usr/bin/env python3
"""Generate the PRESAGE cost-effective-inference result tables from the SAGE-harness
run outputs. Emits auto_table_shortlist.tex, auto_table_recall.tex, auto_presage_macros.tex.

Sources (under $SAGE/results/):
  encoder_zeroshot_T04/  -> text-shortlist run (job 10991242)
  encoder_embed_T04/     -> image-embedding-prototype run (job 10991403)
Recall@k is computed from the text run's per-image shortlists.

Usage:  python gen_presage_tables.py [SAGE_ROOT]
"""
import json, glob, os, sys

SAGE = sys.argv[1] if len(sys.argv) > 1 else "/work/mech-ai-scratch/tirtho/SAGE"
load = lambda p: json.load(open(p)).get("runs", {}) if os.path.exists(p) else {}
txt = load(f"{SAGE}/results/encoder_zeroshot_T04/summary.json")
emb = load(f"{SAGE}/results/encoder_embed_T04/summary.json")

rec = {}
for f in glob.glob(f"{SAGE}/results/encoder_zeroshot_T04/*/*/results.jsonl"):
    rows = [json.loads(l) for l in open(f) if l.strip()]
    if not rows:
        continue
    key = f.split("/")[-3] + "/" + f.split("/")[-2]
    n = len(rows)
    rec[key] = dict(n=n,
                    top1=100 * sum(r['encoder_top1'] == r['gt'] for r in rows) / n,
                    r5=100 * sum(r['gt'] in [c for c, _ in r['encoder_shortlist']] for r in rows) / n)

disp = lambda k: f"{k.split('/')[0]} / {'PV' if k.endswith('plantvillage') else 'PD'}"
order = ["Apple/plantvillage", "Apple/plantdoc", "Corn/plantvillage", "Corn/plantdoc",
         "Soybean/plantvillage", "Tomato/plantvillage", "Tomato/plantdoc"]

rows = []
for k in order:
    t = txt.get(k, {}).get("encoder_top1_acc"); e = emb.get(k, {}).get("encoder_top1_acc")
    if t is None or e is None:
        continue
    rows.append(f"{disp(k)} & {t:.1f} & {e:.1f} & {e - t:+.1f} \\\\")
open("auto_table_shortlist.tex", "w").write(
    "% AUTO-GENERATED by paper/gen_presage_tables.py -- do not edit by hand\n"
    "\\begin{tabular}{lccc}\n\\toprule\nCrop / Set & Text & \\textbf{Image-proto} & $\\Delta$ \\\\\n\\midrule\n"
    + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")

rows = []
for k in order:
    if k not in rec:
        continue
    r = rec[k]
    rows.append(f"{disp(k)} & {r['n']} & {r['top1']:.1f} & {r['r5']:.1f} & {r['r5'] - r['top1']:+.1f} \\\\")
open("auto_table_recall.tex", "w").write(
    "% AUTO-GENERATED by paper/gen_presage_tables.py -- do not edit by hand\n"
    "\\begin{tabular}{lcccc}\n\\toprule\nCrop / Set & $n$ & top-1 & recall@5 & headroom \\\\\n\\midrule\n"
    + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")

# Table 3 (optional): adaptive k-sweep, emitted only once that run exists.
ks_summary = f"{SAGE}/results/adaptive_knn_sweep_T04/summary.json"
if os.path.exists(ks_summary):
    runs = json.load(open(ks_summary)).get("runs", {})
    KS = [0, 1, 4, 8, 16]
    rows = []
    for k in order:
        s = runs.get(k)
        if not s:
            continue
        pk = s["per_k"]
        cells = " & ".join(str(pk.get(str(b), pk.get(b, {})).get("acc", "--")) for b in KS)
        rows.append(f"{disp(k)} & {cells} \\\\")
    if rows:
        open("auto_table_ksweep.tex", "w").write(
            "% AUTO-GENERATED by paper/gen_presage_tables.py -- do not edit by hand\n"
            "\\begin{tabular}{lccccc}\n\\toprule\nCrop / Set & $k{=}0$ & $1$ & $4$ & $8$ & $16$ \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")
        print("wrote auto_table_ksweep.tex")

tc = sum(s.get("total_cost_usd", 0) for s in txt.values())
ec = sum(s.get("total_cost_usd", 0) for s in emb.values())
open("auto_presage_macros.tex", "w").write(
    "\\newcommand{\\costtext}{\\$%.2f}\n\\newcommand{\\costembed}{\\$%.2f}\n"
    "\\newcommand{\\sagecostlo}{\\$18}\n\\newcommand{\\sagecosthi}{\\$35}\n" % (tc, ec))
print(f"wrote tables; text ${tc:.2f}, embed ${ec:.2f}")
